/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id: null, // Not using Identity Pool in this setup
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_ZvOQwEyi1",
  aws_user_pools_web_client_id: "495i4k7kurnalbfou86avkae1t",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: [],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      "REQUIRES_LOWERCASE",
      "REQUIRES_NUMBERS",
      "REQUIRES_UPPERCASE",
    ],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_cloud_logic_custom: [
    {
      name: "FileManagementAPI", // Logical name for the API
      endpoint: "https://3nl4khbr4c.execute-api.us-east-1.amazonaws.com/",
      region: "us-east-1",
    },
  ],
};

export default awsmobile;
